# Generated by Django 5.1.4 on 2024-12-27 07:46

import phonenumber_field.modelfields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('pk_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=100)),
                ('locality', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pin', models.PositiveIntegerField()),
                ('state', models.CharField(choices=[('1', 'Province No. 1'), ('2', 'Madhesh Province'), ('3', 'Bagmati Province'), ('4', 'Gandaki Province'), ('5', 'Lumbini Province'), ('6', 'Karnali Province'), ('7', 'Sudurpashchim Province')], max_length=100)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='NP')),
                ('email', models.EmailField(max_length=254)),
                ('job_city', models.CharField(max_length=100)),
                ('profile_image', models.ImageField(blank=True, upload_to='profileimage')),
                ('my_file', models.FileField(blank=True, upload_to='document')),
            ],
        ),
    ]
